; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200  
upload_speed = 115200

lib_deps = 
    miguelbalboa/MFRC522@^1.4.11
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@^6.21.3

; USB upload configuration
upload_protocol = esptool
upload_port = /dev/cu.usbserial-110

; OTA environment - upload via WiFi
[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 10.10.1.5
upload_flags = 
    --auth=Ayamgeprek
    --port=3232